[profile.default]
src = "src"
solc_version = "0.8.23"
libs = ["lib"]
test = "test"

[fmt]
bracket_spacing = true

[profile.simulation]
test = "fork-test"


# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
